### ISSUE TITLE
Access violation with build shared object

### ISSUE THREAD

**Issue by t-knapp** [riicchhaarrd/CoDExtended#1]
Hello,

I'm trying to build codextended.so. There are some missing files.

*net_chan.c* file is missing, I solved this problem by adding this (and more included files) from this 
https://github.com/id-Software/Quake-III-Arena/blob/master/code/qcommon/net_chan.c project. - Is this correct?

Another problem is in *curl.c*. The included file *curl/types.h* is deprecated since two years and is not included in all *libcurl-** packages on debian/ubuntu. Uncommenting this import does not leet to compiler errors, I assume this file is not needed.

Then I'm able to compile the shared object but on startup, the server crashes with access violation.

> COD MP 1.1 build linux-i386 Nov 13 2003
> ----- FS_Startup -----
> Current search path:
> /home/tknapp/.callofduty/main
> /home/tknapp/codmp/main/zZz_zombies_v6.pk3 (67 files)
> /home/tknapp/codmp/main/pak6.pk3 (3 files)
> /home/tknapp/codmp/main/pak5.pk3 (4858 files)
> /home/tknapp/codmp/main/pak4.pk3 (1668 files)
> /home/tknapp/codmp/main/pak3.pk3 (1992 files)
> /home/tknapp/codmp/main/pak2.pk3 (694 files)
> /home/tknapp/codmp/main/pak1.pk3 (2642 files)
> /home/tknapp/codmp/main/pak0.pk3 (12828 files)
> /home/tknapp/codmp/main
> 
> File Handles:
> 24752 files in pk3 files
> execing default_mp.cfg
> couldn't exec language.cfg
> execing config_mp_server.cfg
> couldn't exec autoexec_mp.cfg
> Hunk_Clear: reset the hunk ok
> Speicherzugriffsfehler (Speicherabzug geschrieben) [access violation (core dumped)]

I got one question left: Where is the code of the downloaded *xtn_module.so*?

Thanks in advance.
t-knapp

**Comment by riicchhaarrd** [comment]
Apparently somehow the sv_netchan didn't get uploaded, I've uploaded it and made sure it's uploaded now.

**Comment by t-knapp** [comment]
Works. Thanks.
