### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by torreserne** [riicchhaarrd/CoDExtended#11]
I have this error at compile /usr/bin/ld: cannot find -lz collect2: error: ld returned 1 exit status can you help me?

**Comment by t-knapp** [comment]
Do you try to compile it on your local machine or in a docker container?

I'll recommend you to use a docker container to compile and run it. The gap in library versions is still increasing and sometimes you wont be able to install the ancient versions of lib xy.

Take a look at this: https://github.com/t-knapp/codmp/tree/main/codextended-buildtime

**Comment by torreserne** [comment]
i compile on vps server

**Comment by t-knapp** [comment]
Okay.

You can use the `ldd` command to check for missing dependencies. https://man7.org/linux/man-pages/man1/ldd.1.html

You can try to compile in docker, but I think you'll end up with same error because the libs are missing on your VPS (target machine) anyway.

**Comment by torreserne** [comment]
i have ldd
 linux-vdso.so.1 (0x00007fff219f5000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f19471bf000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1946e20000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f1946bad000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f19469a9000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1947608000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f194678c000)

**Comment by kungfooman** [comment]
If you miss a lib, just install it. For -lz, it seems to be: zlib1g-dev (quick google)

What distro do you use? Command might just be `sudo apt install zlib1g-dev`

**Comment by torreserne** [comment]
i install, but continue the same error

**Comment by torreserne** [comment]
i use debian stretch

**Comment by torreserne** [comment]
i install zlib1g-dev:i386 and now work fine

**Comment by kungfooman** [comment]
Try other variants (probably first one):

* `sudo apt-get install lib32z1-dev`
* `sudo apt-get install zlib1g-dev`
* `sudo apt-get install libz-dev`

Edit: nice, glad you figured it out

**Comment by torreserne** [comment]
i´m the owner of Titan-Clan servers of cod1, your welcome to visit, thanks

**Comment by torreserne** [comment]
sorry for write on issue close but i want know how to enable and use webserver and mysql
