### ISSUE TITLE
how to enable and use webserver and mysql

### ISSUE THREAD

**Issue by riicchhaarrd** [riicchhaarrd/CoDExtended#12]
sorry for write on issue close but i want know how to enable and use webserver and mysql

_Originally posted by @torreserne in https://github.com/xtnded/codextended/issues/11#issuecomment-971755284_

**Comment by riicchhaarrd** [comment]
For the webserver stuff, that was pretty much just made as a gimmick and doesn't really do that much, I would advise against using it aswell.

To use MySQL build it with the -m flag and then just run the server as usual except you now have some additional scripting functions prefixed with mysql_* you can use to interact with your database.

For an overview of the MySQL scripting functions see
https://github.com/xtnded/codextended/blob/stable/src/scr_mysql.c

Most of it pretty much resembles the MySQL C API and wrap and just forward the arguments and return the result.

**Comment by torreserne** [comment]
Thanks, i´m going to study that
