### ISSUE TITLE
MySQL Server has gone away

### ISSUE THREAD

**Issue by Parnassian** [riicchhaarrd/CoDExtended#4]
@riicchhaarrd 

My server is running fine for multiple days but I always end up with following error.

```
INSERT INTO session (server_id, ip, entnum) VALUES('82','xx.xx.xx.xx','0');
errno = 2006 error = MySQL server has gone away
public_dm.sh: line 2: 26875 Segmentation fault LD_PRELOAD=./codextended.so ./cod_lnxded +set dedicated 2 +exec dedicated.cfg +exec dm.cfg
```

Is it possible to let CoDExtended automatically reconnect to the database?

**Comment by riicchhaarrd** [comment]
It's already supposed to do that I think, altough I think I used a & too many and changed &c to c.
