### ISSUE TITLE
Is it possible to compile targeting 64bit OS?

### ISSUE THREAD

**Issue by marcmascarell** [riicchhaarrd/CoDExtended#6]
Since the trend is to use 64bit (latest Ubuntu does not even have 32bit version) I would like to compile this project to 64bit, which steps should I take?

_(If you are wondering there is a 64bit version of cod_lnxded)_

**Comment by Ingramz** [comment]
@marcmascarell where can that 64bit version be found?

**Comment by riicchhaarrd** [comment]
As far as I know, there is no x64 cod_lnxded executable/binary.
Atleast not for the cod_lnxded versions we're targeting here with this project.

**Comment by marcmascarell** [comment]
True, Im wrong. 

https://linuxgsm.com/lgsm/codserver/

![image](https://user-images.githubusercontent.com/642299/44681081-d64f8f80-aa3f-11e8-9247-ed250ddd9a90.png)

So forget my question. 

Which COD version is targeting the binary in the repo?

**Comment by riicchhaarrd** [comment]
Mainly atm just the 1.1 version, there's in the repo some versions that work for 1.5 / UO for windows and linux (but they're unstable etc), but I kind of abandoned the project since it's mostly done and I don't really have the time anymore.
