### ISSUE TITLE
Cannot download xtn_module.so 

### ISSUE THREAD

**Issue by t-knapp** [riicchhaarrd/CoDExtended#7]
Hi richaarrd,

it's been a while since I used codextended. I'm trying to run it as a docker container and after resolving all dependencies on debian:buster I'm stuck at this point:

Download of xtn_module.so does not work, see the attached cli output.

```
root@65b93cfa6509:/var/codmp# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. LD_PRELOAD=./codextended.so ./cod_lnxded +set dedicated 2 +exec dedicated.cfg
Downloading...

100% [========================================]]
Failed to load './xtn_module.so'
Hunk_Clear: reset the hunk ok
root@65b93cfa6509:/var/codmp# ls -al
total 7612
drwxrwxr-x.  4 root root    4096 Dec 22 15:59 .
drwxr-xr-x. 12 root root    4096 Dec 22 14:15 ..
-rw-r--r--.  1 root root 1564672 Dec 22 13:22 CoDMP.exe
-rw-r--r--.  1 root root 2912155 Dec 22 13:22 CoDSP.exe
-rw-r--r--.  1 root root  462848 Dec 22 13:22 cgamex86.dll
-rw-r--r--.  1 root root  259756 Dec 22 13:22 cod.bmp
-rwxr-xr-x.  1 root root  724648 Dec 22 13:22 cod_lnxded
-rwxr-xr-x.  1 root root  476760 Dec 22 13:22 codextended.so
-rw-r--r--.  1 root root  737280 Dec 22 13:22 gamex86.dll
-rw-r--r--.  1 root root    2285 Dec 22 13:22 localization.txt
drwxr-xr-x.  4 root root    4096 Dec 22 13:22 main
drwxr-xr-x.  2 root root    4096 Dec 22 13:22 miles
-rw-r--r--.  1 root root  370688 Dec 22 13:22 mss32.dll
-rw-r--r--.  1 root root  253952 Dec 22 13:22 uix86.dll
-rw-r--r--.  1 root root     196 Dec 22 15:59 xtn_module.so
root@65b93cfa6509:/var/codmp# cat xtn_module.so 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
root@65b93cfa6509:/var/codmp# 
```

Where is the file hosted or how can I get it?

Kind regards

**Comment by PrawyCoD1** [comment]
Hey man


I'm not php

His discord: bliminse#0352

Regards,
Prawy

wt., 22 gru 2020, 17:07 użytkownik Tobias Knapp <notifications@github.com>
napisał:

**Comment by riicchhaarrd** [comment]
Which version are you using? Stable or the master branch? Linux or Windows, 1.1 or 1.5? A older version e.g the MDLL one? Are you using a customized different version e.g a fork someone else made because I can't recall that it downloaded anything or a xtn_module.so of sorts.

**Comment by t-knapp** [comment]
Turns out, I was using a binary I compiled five years ago. So I picked the binary from your stable branch.

Now it runs version 1.1 on a debian linux but the function 'mysql_get_connection' is missing. So I guess the provided binary is not compiled with MySQL, right?

**Comment by riicchhaarrd** [comment]
Well probably not, but you can compile it yourself just pass the -m flag to ./build.sh
